### ISSUE TITLE
Correções nos Formulários

### ISSUE THREAD

**Issue by cleysonsilvame** [MatheusFranciscone/projeto-multifunctions#1]
## Prevenção de erros

- Na seção de _"Entrada de dados"_ do formulário de _"Cadastro"_ está aceitando letra no textbox de código.
- Na seção de _"Consultar Dados"_ do formulário de _"Cadastro"_ está ocorrendo um erro ao eliminar a lista vazia e o campo para inserir novo dado manualmente está ativo. Sugiro criar um tratamento de erro com uma mensagem para quando clicar em eliminar ele não ocorra o erro.
- Na no formulário de _"Pedidos"_ também está com o erro de que quando exclui a lista fazia, novamente sugiro um tratamento de erro com mensagens ao usuário. 

## Melhorias

- Verifique os _index_ dos elementos para ficar na sequencia.
- Coloque os _buttons_ principais como um _AcceptButton_ nos formulários para quando apertar enter ele ir direto.

<br>

![assinatura-cleyson-silva](https://raw.githubusercontent.com/cleysonsilvame/cleysonsilvame.github.io/master/minha-assinatura/render/assinatura.png)

- ### [Acesse meu GitHub](github.com/cleysonsilvame)
- ### [Acesse meu Instragram](instagram.com/cleysonsilva.me)
- ### [Acesse meu Linkedin](linkedin.com/in/cleyson-silva-639b01188)

**Comment by MatheusFranciscone** [comment]
Olá, Obrigado por sua colaboração!

Irei fazer as atualizações necessárias para um melhor funcionamento do projeto.

## Acesse meus outros meios de contato!

 * ### [Instagram](https://www.instagram.com/_franciscone/);
 * ### [LinkedIn](https://www.linkedin.com/in/matheus-franciscone/);

## Acesse também meus outros repositórios aqui no GitHub!

 * ### [Repositórios](https://github.com/MatheusFranciscone?tab=repositories)

**Comment by cleysonsilvame** [comment]
Precisando estamos aqui!
Qualquer coisa peça um request, será um prazer em ajudar!

<br>

![assinatura-cleyson-silva](https://raw.githubusercontent.com/cleysonsilvame/cleysonsilvame.github.io/master/minha-assinatura/render/assinatura.png)

- ### [Acesse meu GitHub](github.com/cleysonsilvame)
- ### [Acesse meu Instragram](instagram.com/cleysonsilva.me)
- ### [Acesse meu Linkedin](linkedin.com/in/cleyson-silva-639b01188)
